# ============================================================
# 02_plot_cell_nm_R1_sweep_CR.jl
#
# Goal:
# Plot the results generated by:
#
#   01_run_cell_nm_R1_sweep.jl
#
# This script reads:
#
#   docs/data/processed/cell_nm_R1_sweep_R1_sweep.csv
#
# and creates figures showing:
#
#   1. total contrast ratio vs R1_NM;
#   2. compartment-wise contrast ratios vs R1_NM;
#   3. raw compartment signals vs R1_NM;
#   4. zoomed contrast ratio around the estimated R1_NM ≈ 50 s^-1.
#
# Contrast ratio:
#
#   CR = (S_i - S_0) / S_0
#
# where:
#   S_i = signal for a given R1_NM value
#   S_0 = baseline signal when R1_NM equals the background R1.
#
# Run from the repository root with:
#
#   julia +1.11 --project=. docs/scripts/07_cell_neuromelanin_R1_sweep/02_plot_cell_nm_R1_sweep_CR.jl
# ============================================================

using CairoMakie
using DelimitedFiles
using Statistics

# ============================================================
# User parameters
# ============================================================

const OUTPUT_PREFIX = "cell_nm_R1_sweep"

const OUTPUT_DIR = joinpath("docs", "data", "processed")
const FIGURE_DIR = joinpath("docs", "figures")

const INPUT_CSV = joinpath(
    OUTPUT_DIR,
    OUTPUT_PREFIX * "_R1_sweep.csv",
)

const TOTAL_CR_FIG = joinpath(
    FIGURE_DIR,
    OUTPUT_PREFIX * "_CR_total_vs_R1_NM.png",
)

const COMPARTMENT_CR_FIG = joinpath(
    FIGURE_DIR,
    OUTPUT_PREFIX * "_CR_compartments_vs_R1_NM.png",
)

const RAW_SIGNAL_FIG = joinpath(
    FIGURE_DIR,
    OUTPUT_PREFIX * "_raw_signals_vs_R1_NM.png",
)

const ZOOM_CR_FIG = joinpath(
    FIGURE_DIR,
    OUTPUT_PREFIX * "_CR_total_zoom_0_to_120_s.png",
)

# Estimated R1_NM from the supervisor's calculation.
#
# This is used only as a visual reference line.
const ESTIMATED_R1_NM_S = 50.0

# Zoom range around physiologically interesting values.
const ZOOM_R1_MIN = 0.0
const ZOOM_R1_MAX = 120.0

# ============================================================
# CSV helpers
# ============================================================

"""
    read_csv_as_dicts(path)

Read a CSV file written with `DelimitedFiles.writedlm`.

Returns:
- `rows`: vector of dictionaries, one dictionary per data row;
- `header`: vector of column names.
"""
function read_csv_as_dicts(path::String)
    if !isfile(path)
        error("""
        Missing CSV file:

            $path

        Please run the simulation script first:
            julia +1.11 --project=. docs/scripts/07_cell_neuromelanin_R1_sweep/01_run_cell_nm_R1_sweep.jl
        """)
    end

    raw = readdlm(path, ',', String)

    header = vec(raw[1, :])
    data = raw[2:end, :]

    rows = Vector{Dict{String, String}}()

    for i in 1:size(data, 1)
        row = Dict{String, String}()

        for j in 1:length(header)
            row[header[j]] = data[i, j]
        end

        push!(rows, row)
    end

    return rows, header
end

"""
    parse_float(row, key)

Parse one Float64 value from a CSV row dictionary.
"""
function parse_float(row, key)
    value = row[key]

    if value == "NaN" || value == "nan" || value == ""
        return NaN
    end

    return parse(Float64, value)
end

"""
    sort_rows_by_R1(rows)

Sort rows by R1_NM_total_s.
"""
function sort_rows_by_R1(rows)
    return sort(rows; by = row -> parse_float(row, "R1_NM_total_s"))
end

"""
    get_vector(rows, key)

Extract a numeric vector from rows for column `key`.
"""
function get_vector(rows, key)
    return [parse_float(row, key) for row in rows]
end

"""
    get_metadata(rows)

Return basic metadata from the first row.
"""
function get_metadata(rows)
    row = rows[1]

    return (
        cell_swc_name = row["cell_swc_name"],
        nm_swc_name = row["nm_swc_name"],
        R1_background_s = parse_float(row, "R1_background_s"),
        R2_global_s = parse_float(row, "R2_global_s"),
        TE = parse_float(row, "TE"),
        TR = parse_float(row, "TR"),
        diffusivity = parse_float(row, "diffusivity"),
        skip_TR = parse_float(row, "skip_TR"),
    )
end

"""
    filter_R1_range(rows; min_R1, max_R1)

Keep only rows with R1_NM_total_s within the selected range.
"""
function filter_R1_range(rows; min_R1, max_R1)
    return [
        row for row in rows
        if min_R1 <= parse_float(row, "R1_NM_total_s") <= max_R1
    ]
end

# ============================================================
# Plot helpers
# ============================================================

"""
    add_estimated_R1_line!(ax; estimated_R1)

Add a vertical line showing the estimated R1_NM value.
"""
function add_estimated_R1_line!(ax; estimated_R1 = ESTIMATED_R1_NM_S)
    vlines!(
        ax,
        [estimated_R1],
        linestyle = :dash,
        linewidth = 2,
        label = "estimated R1_NM ≈ $(Int(round(estimated_R1))) s⁻¹",
    )
end

"""
    plot_total_CR(rows, metadata)

Plot total contrast ratio as a function of R1_NM.
"""
function plot_total_CR(rows, metadata)
    r1_values = get_vector(rows, "R1_NM_total_s")
    cr_total = get_vector(rows, "CR_total")

    fig = Figure(size = (900, 600))

    ax = Axis(
        fig[1, 1],
        title = "NM-MRI contrast ratio vs neuromelanin R1",
        xlabel = "Neuromelanin R1, total (s⁻¹)",
        ylabel = "CR = (Sᵢ - S₀) / S₀",
    )

    lines!(
        ax,
        r1_values,
        cr_total,
        label = "total signal",
    )

    scatter!(
        ax,
        r1_values,
        cr_total,
    )

    add_estimated_R1_line!(ax)

    axislegend(ax, position = :rb)

    Label(
        fig[2, 1],
        "Baseline: R1_NM = R1_background = $(metadata.R1_background_s) s⁻¹; TE/TR = $(metadata.TE)/$(metadata.TR) ms; R2 global = $(metadata.R2_global_s) s⁻¹",
        tellwidth = false,
        fontsize = 14,
    )

    return fig
end

"""
    plot_compartment_CRs(rows, metadata)

Plot contrast ratios for total, inside cell, outside cell, and NM compartment.
"""
function plot_compartment_CRs(rows, metadata)
    r1_values = get_vector(rows, "R1_NM_total_s")

    cr_total = get_vector(rows, "CR_total")
    cr_inside_cell = get_vector(rows, "CR_inside_cell")
    cr_outside_cell = get_vector(rows, "CR_outside_cell")
    cr_inside_nm = get_vector(rows, "CR_inside_nm")

    fig = Figure(size = (1000, 650))

    ax = Axis(
        fig[1, 1],
        title = "Compartment-wise contrast ratio vs neuromelanin R1",
        xlabel = "Neuromelanin R1, total (s⁻¹)",
        ylabel = "CR = (Sᵢ - S₀) / S₀",
    )

    lines!(
        ax,
        r1_values,
        cr_total,
        label = "total",
    )
    scatter!(ax, r1_values, cr_total)

    lines!(
        ax,
        r1_values,
        cr_inside_cell,
        label = "inside cell",
    )
    scatter!(ax, r1_values, cr_inside_cell)

    lines!(
        ax,
        r1_values,
        cr_outside_cell,
        label = "outside cell",
    )
    scatter!(ax, r1_values, cr_outside_cell)

    lines!(
        ax,
        r1_values,
        cr_inside_nm,
        label = "inside NM",
    )
    scatter!(ax, r1_values, cr_inside_nm)

    add_estimated_R1_line!(ax)

    axislegend(ax, position = :rb)

    Label(
        fig[2, 1],
        "Baseline: R1_NM = $(metadata.R1_background_s) s⁻¹; vertical dashed line: estimated R1_NM ≈ $(ESTIMATED_R1_NM_S) s⁻¹",
        tellwidth = false,
        fontsize = 14,
    )

    return fig
end

"""
    plot_raw_signals(rows, metadata)

Plot raw compartment signals as a function of R1_NM.
"""
function plot_raw_signals(rows, metadata)
    r1_values = get_vector(rows, "R1_NM_total_s")

    total_signal = get_vector(rows, "total_signal")
    inside_cell_signal = get_vector(rows, "inside_cell_signal")
    outside_cell_signal = get_vector(rows, "outside_cell_signal")
    inside_nm_signal = get_vector(rows, "inside_nm_signal")

    fig = Figure(size = (1000, 650))

    ax = Axis(
        fig[1, 1],
        title = "Raw gradient-echo signals vs neuromelanin R1",
        xlabel = "Neuromelanin R1, total (s⁻¹)",
        ylabel = "Signal magnitude",
    )

    lines!(
        ax,
        r1_values,
        total_signal,
        label = "total",
    )
    scatter!(ax, r1_values, total_signal)

    lines!(
        ax,
        r1_values,
        inside_cell_signal,
        label = "inside cell",
    )
    scatter!(ax, r1_values, inside_cell_signal)

    lines!(
        ax,
        r1_values,
        outside_cell_signal,
        label = "outside cell",
    )
    scatter!(ax, r1_values, outside_cell_signal)

    lines!(
        ax,
        r1_values,
        inside_nm_signal,
        label = "inside NM",
    )
    scatter!(ax, r1_values, inside_nm_signal)

    add_estimated_R1_line!(ax)

    axislegend(ax, position = :rb)

    Label(
        fig[2, 1],
        "Raw signals are shown to check that the CR trend is not caused by numerical artefacts.",
        tellwidth = false,
        fontsize = 14,
    )

    return fig
end

"""
    plot_total_CR_zoom(rows, metadata)

Plot total contrast ratio zoomed around low R1_NM values.
"""
function plot_total_CR_zoom(rows, metadata)
    zoom_rows = filter_R1_range(
        rows;
        min_R1 = ZOOM_R1_MIN,
        max_R1 = ZOOM_R1_MAX,
    )

    r1_values = get_vector(zoom_rows, "R1_NM_total_s")
    cr_total = get_vector(zoom_rows, "CR_total")

    fig = Figure(size = (900, 600))

    ax = Axis(
        fig[1, 1],
        title = "NM-MRI contrast ratio near estimated R1_NM",
        xlabel = "Neuromelanin R1, total (s⁻¹)",
        ylabel = "CR = (Sᵢ - S₀) / S₀",
    )

    lines!(
        ax,
        r1_values,
        cr_total,
        label = "total signal",
    )

    scatter!(
        ax,
        r1_values,
        cr_total,
    )

    add_estimated_R1_line!(ax)

    axislegend(ax, position = :rb)

    Label(
        fig[2, 1],
        "Zoom range: $(ZOOM_R1_MIN)–$(ZOOM_R1_MAX) s⁻¹. Baseline S₀ is R1_NM = $(metadata.R1_background_s) s⁻¹.",
        tellwidth = false,
        fontsize = 14,
    )

    return fig
end

# ============================================================
# Main script
# ============================================================

function main()
    println("============================================================")
    println("02 — Plot cell + neuromelanin R1 sweep contrast ratio")
    println("============================================================")

    mkpath(FIGURE_DIR)

    println("\nInput CSV:")
    println("  ", INPUT_CSV)

    rows, header = read_csv_as_dicts(INPUT_CSV)
    rows = sort_rows_by_R1(rows)

    if isempty(rows)
        error("Input CSV contains no data rows.")
    end

    metadata = get_metadata(rows)

    println("\nDetected metadata")
    println("-----------------")
    println("Cell SWC:        ", metadata.cell_swc_name)
    println("NM SWC:          ", metadata.nm_swc_name)
    println("R1 background:   ", metadata.R1_background_s, " s^-1")
    println("R2 global:       ", metadata.R2_global_s, " s^-1")
    println("TE/TR:           ", metadata.TE, " / ", metadata.TR, " ms")
    println("diffusivity:     ", metadata.diffusivity)
    println("skip_TR:         ", metadata.skip_TR)

    r1_values = get_vector(rows, "R1_NM_total_s")

    println("\nR1_NM values:")
    println(r1_values)

    println("\nPlotting total CR vs R1_NM...")

    fig_total = plot_total_CR(
        rows,
        metadata,
    )

    save(TOTAL_CR_FIG, fig_total)
    display(fig_total)

    println("Saved figure:")
    println("  ", TOTAL_CR_FIG)

    println("\nPlotting compartment-wise CR vs R1_NM...")

    fig_compartments = plot_compartment_CRs(
        rows,
        metadata,
    )

    save(COMPARTMENT_CR_FIG, fig_compartments)
    display(fig_compartments)

    println("Saved figure:")
    println("  ", COMPARTMENT_CR_FIG)

    println("\nPlotting raw signals vs R1_NM...")

    fig_raw = plot_raw_signals(
        rows,
        metadata,
    )

    save(RAW_SIGNAL_FIG, fig_raw)
    display(fig_raw)

    println("Saved figure:")
    println("  ", RAW_SIGNAL_FIG)

    println("\nPlotting zoomed total CR around estimated R1_NM...")

    fig_zoom = plot_total_CR_zoom(
        rows,
        metadata,
    )

    save(ZOOM_CR_FIG, fig_zoom)
    display(fig_zoom)

    println("Saved figure:")
    println("  ", ZOOM_CR_FIG)

    println("\nSummary")
    println("-------")

    cr_total = get_vector(rows, "CR_total")
    cr_inside_nm = get_vector(rows, "CR_inside_nm")

    max_index = argmax(cr_total)

    println("Maximum total CR:")
    println("  R1_NM = ", r1_values[max_index], " s^-1")
    println("  CR_total = ", cr_total[max_index])

    estimated_index = findmin(abs.(r1_values .- ESTIMATED_R1_NM_S))[2]

    println("\nClosest simulated value to estimated R1_NM:")
    println("  estimated R1_NM = ", ESTIMATED_R1_NM_S, " s^-1")
    println("  simulated R1_NM = ", r1_values[estimated_index], " s^-1")
    println("  CR_total = ", cr_total[estimated_index])
    println("  CR_inside_NM = ", cr_inside_nm[estimated_index])

    println("\nPlotting completed successfully.")
end

main()