# ============================================================
# 02_plot_single_substrate_DWI.jl
#
# Goal:
# Plot the results generated by:
#
#   01_run_single_substrate_DWI.jl
#
# This script reads:
#
#   docs/data/processed/<OUTPUT_PREFIX>_signal.csv
#   docs/data/processed/<OUTPUT_PREFIX>_ADC_summary.csv
#
# and creates:
#
#   1. normalized signal S(b)/S(0) vs b;
#   2. log-normalized signal ln(S/S0) with ADC fits;
#   3. ADC summary plot.
#
# Run from the repository root with:
#
#   julia +1.11 --project=. docs/scripts/05_general_substrate_simulation/02_plot_single_substrate_dwi.jl
# ============================================================

using CairoMakie
using DelimitedFiles
using Statistics

# ============================================================
# User parameters
# ============================================================

# Must match the OUTPUT_PREFIX used in:
#
#   01_run_single_substrate_DWI.jl
#
const OUTPUT_PREFIX = "single_substrate_DWI"

const OUTPUT_DIR = joinpath("docs", "data", "processed")
const FIGURE_DIR = joinpath("docs", "figures")

const SIGNAL_CSV = joinpath(
    OUTPUT_DIR,
    OUTPUT_PREFIX * "_signal.csv",
)

const SUMMARY_CSV = joinpath(
    OUTPUT_DIR,
    OUTPUT_PREFIX * "_ADC_summary.csv",
)

const NORMALIZED_SIGNAL_FIG = joinpath(
    FIGURE_DIR,
    OUTPUT_PREFIX * "_normalized_signal_vs_b.png",
)

const LOG_SIGNAL_FIT_FIG = joinpath(
    FIGURE_DIR,
    OUTPUT_PREFIX * "_ln_signal_fit_vs_b.png",
)

const ADC_SUMMARY_FIG = joinpath(
    FIGURE_DIR,
    OUTPUT_PREFIX * "_ADC_summary.png",
)

# ============================================================
# CSV helpers
# ============================================================

"""
    read_csv_as_dicts(path)

Read a CSV file written with `DelimitedFiles.writedlm`.

Returns:
- `rows`: vector of dictionaries, one dictionary per row;
- `header`: vector of column names.

All values are initially read as strings. Numeric values are parsed later
only when needed.
"""
function read_csv_as_dicts(path::String)
    if !isfile(path)
        error("""
        Missing CSV file:

            $path

        Please run the simulation script first:
            julia +1.11 --project=. docs/scripts/05_general_substrate_simulation/01_run_single_substrate_DWI.jl
        """)
    end

    raw = readdlm(path, ',', String)

    header = vec(raw[1, :])
    data = raw[2:end, :]

    rows = Vector{Dict{String, String}}()

    for i in 1:size(data, 1)
        row = Dict{String, String}()

        for j in 1:length(header)
            row[header[j]] = data[i, j]
        end

        push!(rows, row)
    end

    return rows, header
end

"""
    parse_float(row, key)

Parse one numeric value from a CSV row dictionary.
"""
function parse_float(row, key)
    return parse(Float64, row[key])
end

"""
    parse_int(row, key)

Parse one integer value from a CSV row dictionary.
"""
function parse_int(row, key)
    return parse(Int, row[key])
end

"""
    unique_preserve_order(values)

Return unique values while preserving their first appearance order.
"""
function unique_preserve_order(values)
    out = eltype(values)[]

    for value in values
        if !(value in out)
            push!(out, value)
        end
    end

    return out
end

"""
    filter_signal_rows(rows; TE, direction_name, repeat_index)

Filter detailed signal rows for one TE, one direction and one repeat.
"""
function filter_signal_rows(rows; TE, direction_name, repeat_index)
    return [
        row for row in rows
        if parse_float(row, "TE") == TE &&
           row["direction_name"] == direction_name &&
           parse_int(row, "repeat") == repeat_index
    ]
end

"""
    sort_rows_by_b(rows)

Sort signal rows by b-value.
"""
function sort_rows_by_b(rows)
    return sort(rows; by = row -> parse_float(row, "b"))
end

"""
    get_signal_vectors(rows)

Extract b-values, normalized signal, ln(S/S0), and fitted ln(S/S0)
from filtered rows.
"""
function get_signal_vectors(rows)
    sorted_rows = sort_rows_by_b(rows)

    bvals = [parse_float(row, "b") for row in sorted_rows]
    normalized = [parse_float(row, "normalized_signal") for row in sorted_rows]
    ln_signal = [parse_float(row, "ln_S_over_S0") for row in sorted_rows]
    fit_ln = [parse_float(row, "fitted_ln_S_over_S0") for row in sorted_rows]

    return bvals, normalized, ln_signal, fit_ln
end

"""
    get_mean_adc_by_direction(summary_rows, TE)

Compute the mean ADC per direction for one TE across repeats.

Returns:
- `direction_names`
- `mean_adc`
- `std_adc`
"""
function get_mean_adc_by_direction(summary_rows, TE)
    rows_TE = [
        row for row in summary_rows
        if parse_float(row, "TE") == TE
    ]

    direction_names = unique_preserve_order([row["direction_name"] for row in rows_TE])

    mean_adc = Float64[]
    std_adc = Float64[]

    for direction_name in direction_names
        values = [
            parse_float(row, "ADC")
            for row in rows_TE
            if row["direction_name"] == direction_name
        ]

        push!(mean_adc, mean(values))

        if length(values) > 1
            push!(std_adc, std(values))
        else
            push!(std_adc, 0.0)
        end
    end

    return direction_names, mean_adc, std_adc
end

# ============================================================
# Plotting
# ============================================================

"""
    plot_normalized_signal(signal_rows, TE, repeat_index, direction_names)

Plot S(b)/S(0) vs b for all directions at one TE and repeat.
"""
function plot_normalized_signal(signal_rows, TE, repeat_index, direction_names)
    fig = Figure(size = (900, 600))

    ax = Axis(
        fig[1, 1],
        title = "Single-substrate DWI: normalized signal",
        xlabel = "b",
        ylabel = "S(b)/S(0)",
    )

    for direction_name in direction_names
        rows = filter_signal_rows(
            signal_rows;
            TE = TE,
            direction_name = direction_name,
            repeat_index = repeat_index,
        )

        bvals, normalized, _, _ = get_signal_vectors(rows)

        lines!(
            ax,
            bvals,
            normalized,
            label = direction_name,
        )

        scatter!(
            ax,
            bvals,
            normalized,
        )
    end

    axislegend(ax, position = :rb)

    return fig
end

"""
    plot_log_signal_fit(signal_rows, TE, repeat_index, direction_names)

Plot ln(S/S0) and fitted ADC lines for all directions.
"""
function plot_log_signal_fit(signal_rows, TE, repeat_index, direction_names)
    fig = Figure(size = (900, 600))

    ax = Axis(
        fig[1, 1],
        title = "Single-substrate DWI: ADC fit",
        xlabel = "b",
        ylabel = "ln(S(b)/S(0))",
    )

    for direction_name in direction_names
        rows = filter_signal_rows(
            signal_rows;
            TE = TE,
            direction_name = direction_name,
            repeat_index = repeat_index,
        )

        bvals, _, ln_signal, fit_ln = get_signal_vectors(rows)

        scatter!(
            ax,
            bvals,
            ln_signal,
            label = "data " * direction_name,
        )

        lines!(
            ax,
            bvals,
            fit_ln,
            label = "fit " * direction_name,
        )
    end

    axislegend(ax, position = :lb)

    return fig
end

"""
    plot_adc_summary(summary_rows, TE)

Plot mean ADC per direction for one TE.
"""
function plot_adc_summary(summary_rows, TE)
    direction_names, mean_adc, std_adc = get_mean_adc_by_direction(
        summary_rows,
        TE,
    )

    fig = Figure(size = (700, 500))

    ax = Axis(
        fig[1, 1],
        title = "Single-substrate DWI: ADC summary",
        xlabel = "Diffusion direction",
        ylabel = "ADC",
        xticks = (1:length(direction_names), direction_names),
    )

    barplot!(
        ax,
        1:length(direction_names),
        mean_adc,
    )

    # Error bars are useful only if there are several repeats.
    if any(std_adc .> 0)
        errorbars!(
            ax,
            1:length(direction_names),
            mean_adc,
            std_adc,
        )
    end

    return fig
end

# ============================================================
# Main script
# ============================================================

function main()
    println("============================================================")
    println("02 — Plot single-substrate DWI results")
    println("============================================================")

    mkpath(FIGURE_DIR)

    println("\nInput files:")
    println("Signal CSV:  ", SIGNAL_CSV)
    println("Summary CSV: ", SUMMARY_CSV)

    signal_rows, _ = read_csv_as_dicts(SIGNAL_CSV)
    summary_rows, _ = read_csv_as_dicts(SUMMARY_CSV)

    if isempty(signal_rows)
        error("Signal CSV contains no data rows.")
    end

    if isempty(summary_rows)
        error("Summary CSV contains no data rows.")
    end

    TE_values = unique_preserve_order([
        parse_float(row, "TE")
        for row in signal_rows
    ])

    repeat_values = unique_preserve_order([
        parse_int(row, "repeat")
        for row in signal_rows
    ])

    direction_names = unique_preserve_order([
        row["direction_name"]
        for row in signal_rows
    ])

    # For a simple default plot, use the first TE and first repeat.
    # The CSV still contains all TE/repeat values if several were simulated.
    TE_to_plot = TE_values[1]
    repeat_to_plot = repeat_values[1]

    println("\nDetected values:")
    println("TE values:        ", TE_values)
    println("repeats:          ", repeat_values)
    println("directions:       ", direction_names)
    println("TE plotted:       ", TE_to_plot)
    println("repeat plotted:   ", repeat_to_plot)

    println("\nPlotting normalized signal...")

    fig_signal = plot_normalized_signal(
        signal_rows,
        TE_to_plot,
        repeat_to_plot,
        direction_names,
    )

    save(NORMALIZED_SIGNAL_FIG, fig_signal)
    display(fig_signal)

    println("Saved figure:")
    println("  ", NORMALIZED_SIGNAL_FIG)

    println("\nPlotting log-signal ADC fit...")

    fig_log = plot_log_signal_fit(
        signal_rows,
        TE_to_plot,
        repeat_to_plot,
        direction_names,
    )

    save(LOG_SIGNAL_FIT_FIG, fig_log)
    display(fig_log)

    println("Saved figure:")
    println("  ", LOG_SIGNAL_FIT_FIG)

    println("\nPlotting ADC summary...")

    fig_adc = plot_adc_summary(
        summary_rows,
        TE_to_plot,
    )

    save(ADC_SUMMARY_FIG, fig_adc)
    display(fig_adc)

    println("Saved figure:")
    println("  ", ADC_SUMMARY_FIG)

    println("\nPlotting completed successfully.")
end

main()