# ============================================================
# 03_plot_cell_neuromelanin_signals.jl
#
# Goal:
# Plot the compartment-wise gradient-echo signals generated by:
#
#   02_run_cell_neuromelanin_gradient_echo.jl
#
# The input CSV contains one row per neuromelanin R1 condition.
#
# This script plots:
#   1. total signal;
#   2. inside cell signal;
#   3. outside cell signal;
#   4. inside neuromelanin signal;
#   5. normalized signal changes relative to the first NM R1 condition.
#
# Run from the repository root with:
#
#   julia +1.11 --project=. docs/scripts/06_two_substrate_cell_neuromelanin/03_plot_cell_neuromelanin_signals.jl
# ============================================================

using CairoMakie
using DelimitedFiles
using Statistics

# ============================================================
# User parameters
# ============================================================

# Must match the OUTPUT_PREFIX used in:
#
#   02_run_cell_neuromelanin_gradient_echo.jl
#
const OUTPUT_PREFIX = "cell_r19_nm_r15"

const OUTPUT_DIR = joinpath("docs", "data", "processed")
const FIGURE_DIR = joinpath("docs", "figures")

const INPUT_CSV = joinpath(
    OUTPUT_DIR,
    OUTPUT_PREFIX * "_gradient_echo_compartment_signals.csv",
)

const ABSOLUTE_SIGNAL_FIG = joinpath(
    FIGURE_DIR,
    OUTPUT_PREFIX * "_gradient_echo_absolute_compartment_signals.png",
)

const NORMALIZED_SIGNAL_FIG = joinpath(
    FIGURE_DIR,
    OUTPUT_PREFIX * "_gradient_echo_normalized_compartment_signals.png",
)

const NM_ONLY_FIG = joinpath(
    FIGURE_DIR,
    OUTPUT_PREFIX * "_gradient_echo_neuromelanin_signal.png",
)

# ============================================================
# CSV helpers
# ============================================================

"""
    read_csv_as_dicts(path)

Read a CSV file written with `DelimitedFiles.writedlm`.

Returns:
- `rows`: vector of dictionaries, one dictionary per data row;
- `header`: vector of column names.
"""
function read_csv_as_dicts(path::String)
    if !isfile(path)
        error("""
        Missing input CSV:

            $path

        Please run the simulation script first:

            julia +1.11 --project=. docs/scripts/06_two_substrate_cell_neuromelanin/02_run_cell_neuromelanin_gradient_echo.jl
        """)
    end

    raw = readdlm(path, ',', String)

    header = vec(raw[1, :])
    data = raw[2:end, :]

    rows = Vector{Dict{String, String}}()

    for i in 1:size(data, 1)
        row = Dict{String, String}()

        for j in eachindex(header)
            row[header[j]] = data[i, j]
        end

        push!(rows, row)
    end

    return rows, header
end

"""
    parse_float(row, key)

Parse a Float64 value from a row dictionary.
"""
function parse_float(row, key)
    return parse(Float64, row[key])
end

"""
    normalize_by_first_value(values)

Normalize a vector by its first value.
"""
function normalize_by_first_value(values)
    v0 = values[1]

    if isnan(v0) || v0 == 0
        return fill(NaN, length(values))
    end

    return values ./ v0
end

"""
    sort_rows_by_nm_R1(rows)

Sort rows by neuromelanin R1 value.
"""
function sort_rows_by_nm_R1(rows)
    return sort(rows; by = row -> parse_float(row, "nm_R1_inside"))
end

"""
    extract_signal_vectors(rows)

Extract NM R1 values and compartment signals from the CSV rows.

Returns:
- `nm_R1`
- `total_signal`
- `inside_cell_signal`
- `outside_cell_signal`
- `inside_nm_signal`
"""
function extract_signal_vectors(rows)
    sorted_rows = sort_rows_by_nm_R1(rows)

    nm_R1 = [
        parse_float(row, "nm_R1_inside")
        for row in sorted_rows
    ]

    total_signal = [
        parse_float(row, "total_signal")
        for row in sorted_rows
    ]

    inside_cell_signal = [
        parse_float(row, "inside_cell_signal")
        for row in sorted_rows
    ]

    outside_cell_signal = [
        parse_float(row, "outside_cell_signal")
        for row in sorted_rows
    ]

    inside_nm_signal = [
        parse_float(row, "inside_neuromelanin_signal")
        for row in sorted_rows
    ]

    return (
        nm_R1 = nm_R1,
        total = total_signal,
        inside_cell = inside_cell_signal,
        outside_cell = outside_cell_signal,
        inside_neuromelanin = inside_nm_signal,
    )
end

# ============================================================
# Plotting functions
# ============================================================

"""
    plot_absolute_signals(signals)

Plot absolute compartment-wise signals as a function of NM R1.
"""
function plot_absolute_signals(signals)
    fig = Figure(size = (900, 600))

    ax = Axis(
        fig[1, 1],
        title = "Gradient-echo compartment signals",
        xlabel = "Neuromelanin R1 inside (ms⁻¹)",
        ylabel = "Signal magnitude",
    )

    lines!(
        ax,
        signals.nm_R1,
        signals.total,
        label = "total",
    )
    scatter!(ax, signals.nm_R1, signals.total)

    lines!(
        ax,
        signals.nm_R1,
        signals.inside_cell,
        label = "inside cell",
    )
    scatter!(ax, signals.nm_R1, signals.inside_cell)

    lines!(
        ax,
        signals.nm_R1,
        signals.outside_cell,
        label = "outside cell",
    )
    scatter!(ax, signals.nm_R1, signals.outside_cell)

    lines!(
        ax,
        signals.nm_R1,
        signals.inside_neuromelanin,
        label = "inside neuromelanin",
    )
    scatter!(ax, signals.nm_R1, signals.inside_neuromelanin)

    axislegend(ax, position = :rt)

    return fig
end

"""
    plot_normalized_signals(signals)

Plot compartment-wise signals normalized to the first NM R1 condition.
"""
function plot_normalized_signals(signals)
    total_norm = normalize_by_first_value(signals.total)
    inside_cell_norm = normalize_by_first_value(signals.inside_cell)
    outside_cell_norm = normalize_by_first_value(signals.outside_cell)
    inside_nm_norm = normalize_by_first_value(signals.inside_neuromelanin)

    fig = Figure(size = (900, 600))

    ax = Axis(
        fig[1, 1],
        title = "Normalized gradient-echo compartment signals",
        xlabel = "Neuromelanin R1 inside (ms⁻¹)",
        ylabel = "Signal / signal at first NM R1",
    )

    lines!(
        ax,
        signals.nm_R1,
        total_norm,
        label = "total",
    )
    scatter!(ax, signals.nm_R1, total_norm)

    lines!(
        ax,
        signals.nm_R1,
        inside_cell_norm,
        label = "inside cell",
    )
    scatter!(ax, signals.nm_R1, inside_cell_norm)

    lines!(
        ax,
        signals.nm_R1,
        outside_cell_norm,
        label = "outside cell",
    )
    scatter!(ax, signals.nm_R1, outside_cell_norm)

    lines!(
        ax,
        signals.nm_R1,
        inside_nm_norm,
        label = "inside neuromelanin",
    )
    scatter!(ax, signals.nm_R1, inside_nm_norm)

    axislegend(ax, position = :rt)

    return fig
end

"""
    plot_neuromelanin_signal(signals)

Plot only the neuromelanin signal, both absolute and normalized.

This makes the local NM effect easier to inspect.
"""
function plot_neuromelanin_signal(signals)
    inside_nm_norm = normalize_by_first_value(signals.inside_neuromelanin)

    fig = Figure(size = (900, 600))

    ax1 = Axis(
        fig[1, 1],
        title = "Inside neuromelanin signal",
        xlabel = "Neuromelanin R1 inside (ms⁻¹)",
        ylabel = "Signal magnitude",
    )

    lines!(
        ax1,
        signals.nm_R1,
        signals.inside_neuromelanin,
        label = "absolute",
    )
    scatter!(ax1, signals.nm_R1, signals.inside_neuromelanin)

    axislegend(ax1, position = :rt)

    ax2 = Axis(
        fig[2, 1],
        title = "Inside neuromelanin signal normalized",
        xlabel = "Neuromelanin R1 inside (ms⁻¹)",
        ylabel = "Signal / signal at first NM R1",
    )

    lines!(
        ax2,
        signals.nm_R1,
        inside_nm_norm,
        label = "normalized",
    )
    scatter!(ax2, signals.nm_R1, inside_nm_norm)

    axislegend(ax2, position = :rt)

    return fig
end

# ============================================================
# Main script
# ============================================================

function main()
    println("============================================================")
    println("03 — Plot cell + neuromelanin gradient-echo signals")
    println("============================================================")

    mkpath(FIGURE_DIR)

    println("\nInput CSV:")
    println("  ", INPUT_CSV)

    rows, header = read_csv_as_dicts(INPUT_CSV)

    if isempty(rows)
        error("Input CSV contains no data rows.")
    end

    println("\nDetected columns:")
    for col in header
        println("  ", col)
    end

    signals = extract_signal_vectors(rows)

    println("\nDetected NM R1 values:")
    println(signals.nm_R1)

    println("\nSignals:")
    for i in eachindex(signals.nm_R1)
        println("NM R1 = ", signals.nm_R1[i])
        println("  total:               ", signals.total[i])
        println("  inside cell:         ", signals.inside_cell[i])
        println("  outside cell:        ", signals.outside_cell[i])
        println("  inside neuromelanin: ", signals.inside_neuromelanin[i])
    end

    println("\nPlotting absolute compartment signals...")
    fig_absolute = plot_absolute_signals(signals)

    save(ABSOLUTE_SIGNAL_FIG, fig_absolute)
    display(fig_absolute)

    println("Saved figure:")
    println("  ", ABSOLUTE_SIGNAL_FIG)

    println("\nPlotting normalized compartment signals...")
    fig_normalized = plot_normalized_signals(signals)

    save(NORMALIZED_SIGNAL_FIG, fig_normalized)
    display(fig_normalized)

    println("Saved figure:")
    println("  ", NORMALIZED_SIGNAL_FIG)

    println("\nPlotting neuromelanin-only signal...")
    fig_nm = plot_neuromelanin_signal(signals)

    save(NM_ONLY_FIG, fig_nm)
    display(fig_nm)

    println("Saved figure:")
    println("  ", NM_ONLY_FIG)

    println("\nInterpretation guide")
    println("--------------------")
    println("The absolute signal plot shows the raw magnitude of each compartment.")
    println("The normalized plot shows how each compartment changes relative to")
    println("the first NM R1 condition.")
    println("")
    println("If changing NM R1 mainly affects the inside-neuromelanin signal,")
    println("then the NM compartment is driving the observed change.")
    println("")
    println("If the total signal also changes, this suggests that local NM")
    println("relaxation contributes measurably to the combined gradient-echo signal.")

    println("\nPlotting completed successfully.")
end

main()